# Generated by Django 5.0.4 on 2024-04-18 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ABM', 'Accountancy Business Management'), ('GAS', 'General Academics Strand'), ('HUMSS', 'Humanities and Social Sciences'), ('STEM', 'Science Technology Engineering and Mathematics'), ('TVL', 'Technical Vocational Livelihood')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('studentNumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('coachNumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], default='2023-24', max_length=50)),
                ('studentNumber', models.CharField(editable=False, max_length=50, unique=True)),
                ('LRN', models.PositiveIntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('addrs', models.CharField(max_length=100)),
                ('gradeLevel', models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=50)),
                ('section', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strand')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.strand')),
            ],
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachNumber', models.CharField(editable=False, max_length=50, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=10)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('addrs', models.CharField(max_length=50)),
                ('cpNum', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strand')),
                ('subject', models.ManyToManyField(related_name='coaches', to='main.subject')),
            ],
        ),
    ]
