# Generated by Django 5.0.4 on 2024-04-19 02:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.ImageField(blank=True, upload_to='Attendance')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coaches')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strand')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name_plural': 'Attendance QR',
            },
        ),
        migrations.CreateModel(
            name='Attendance_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coaches')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
            options={
                'verbose_name_plural': 'Attendance List',
            },
        ),
    ]
