# Generated by Django 5.0.4 on 2024-04-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendance_attendance_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
