# Generated by Django 5.0.4 on 2024-04-20 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attendance_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
        ),
    ]
